version: "3.9"
services:
  golang:
    container_name: golang
    image: coderbillzay/crud-go
    ports:
      - '8000:8000'
    volumes:
      - ./:/server
    restart: always
    links:
      - db

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=golang
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  jenkins:
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /.jekins/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - ./jenkins/var/run/docker.sock:/var/run/docker.sock